### ISSUE TITLE
Non-Reflected Attributes

### ISSUE THREAD

**Issue by JJ1iN** [LAMXkE/oneM2M-Data-Model-Design-Tool#18]
**이하 내용, 포함되어야하는 Attributes**

- ACP - `creator`(Delete 必)
- AE - `announceSyncType`
- CNT - `announceSyncType`
- GRP - `announceTo`, `announcedAttribute`, `announceSyncType`, `maxNrOfMembers`, `memberIDs`, `membersAccessControlPolicyIDs`, `groupName`
- SUB - 설정이 안되어있음!

Q. `creator`는 TS-0004에는 Data Type: `ID`로 나와있는데 `boolean`으로 가는지?

**Comment by LAMXkE** [comment]
creator의 경우 request는 null을 보내야 생성됨
cr 속성을 설정하고 싶으면 생성 요청시 cr: null이 아니면 reject하도록 되어있음. 
임의의 값을 삽입하면 안됨. Originator의 값을 CSE가 속성에 설정함.
따라서 생성할지 말지 결정하도록 boolean으로 설정함
