### ISSUE TITLE
Bug when refreshing browser

### ISSUE THREAD

**Issue by LAMXkE** [LAMXkE/oneM2M-Data-Model-Design-Tool#7]
저장한 상태로 새로고침하면 선택된 UI 박스는 그대론데 attr설정창은 없는 버그
저장할 때 selected를 해제하는 과정이 필요할 듯

**Comment by hh6196** [comment]
Created 사이클에서 갱신하는 App.vue 오브젝트 cse1의 정보를 이용해서 UI represent 컴포넌트에 갱신하면 좋지 않을까요?
Sessionstorage에서 refresh 할때마다 오브젝트 cse1에 계속 변경된 정보 load하기 때문에 selected 정보도 포함되어 있고 사용하시면 될 것 같습니다.

**Comment by LAMXkE** [comment]
fixed
